pool:
  vmImage: 'ubuntu-latest'
stages:
    - stage: Build
      jobs:
          - job: 'j1'
            steps:
            - task: ServiceNow-DevOps-Agent-Job-Notification@1
              inputs:
                connectedServiceName: 'amarchange'
                Phase: 'STARTED'
            - task: ServiceNow-DevOps-Agent-Job-Notification@1
              inputs:
                connectedServiceName: 'amarchange'
                Phase: 'COMPLETED'
    - stage: Test
      jobs:
          - job: 'j2'
            steps:
            - task: ServiceNow-DevOps-Agent-Job-Notification@1
              inputs:
                connectedServiceName: 'amarchange'
                upstream: 'j1'
                Phase: 'STARTED'
            - task: ServiceNow-DevOps-Agent-Job-Notification@1
              inputs:
                connectedServiceName: 'amarchange'
                upstream: 'j1'
                Phase: 'COMPLETED'
    - stage: deploy
      jobs:
          - job: 'j3'
            pool: server
            steps:
            - task: ServiceNow-DevOps-Server-Job-Notification@1
              inputs:
                connectedServiceName: 'amarchange'
                UpstreamJob: 'j2'
                Phase: 'STARTED'
            - task: ServiceNow-DevOps-Server-Change-Acceleration@1
              inputs:
                connectedServiceName: 'amarchange'
                UpstreamJob: 'j2'
            - task: ServiceNow-DevOps-Server-Job-Notification@1
              inputs:
                connectedServiceName: 'amarchange'
                UpstreamJob: 'j2'
                Phase: 'COMPLETED'
    - stage: pkg
      jobs:
          - job: 'j4'
            pool: server
            steps:
            - task: ServiceNow-DevOps-Server-Job-Notification@1
              inputs:
                connectedServiceName: 'amarchange'
                UpstreamJob: 'j3'
                Phase: 'STARTED'
            - task: ServiceNow-DevOps-Server-Package-Registration@1
              inputs:
                connectedServiceName: 'amarchange'
                packageRegistrationPayload: |
                  {
                      "name": "pkg$(build.buildId)",
                      "artifacts": [
                      {
                          "name": "az-artifact1",
                          "repositoryName": "repo1",
                          "version": "1.$(build.buildId)",
                          "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                          "taskExecutionNumber":"$(build.buildId)",
                          "stageName":"$(system.jobDisplayName)",
                          "branchName":"$(build.sourceBranchName)"
                      }],
                      "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                      "taskExecutionNumber":"$(build.buildId)",
                      "stageName":"$(system.jobDisplayName)",
                      "branchName":"$(build.sourceBranchName)"
                  }
                artifactToolIdExists: false
            - task: ServiceNow-DevOps-Server-Artifact-Registration@1
              inputs:
                connectedServiceName: 'amarchange'
                artifactRegistrationPayload: |
                  {
                     "artifacts": [
                        {
                           "name": "az-artifact1",
                           "version": "1.$(build.buildId)",
                           "semanticVersion": "1.$(build.buildId).0",
                           "repositoryName": "repo1"
                        },
                        {
                           "name": "az-artifact2",
                           "version": "1.$(build.buildId)",
                           "semanticVersion": "1.$(build.buildId).0",
                           "repositoryName": "repo2"
                        }
                     ],
                     "pipelineName": "$(system.teamProject)/$(build.definitionName)",
                     "taskExecutionNumber": "$(build.buildId)",
                     "stageName": "$(system.jobDisplayName)",
                     "branchName": "$(build.sourceBranchName)"
                  }
                artifactToolIdExists: false
            - task: ServiceNow-DevOps-Server-Job-Notification@1
              inputs:
                connectedServiceName: 'amarchange'
                UpstreamJob: 'j3'
                Phase: 'COMPLETED'
    - stage: dummy
      jobs:
          - job: 'j5'
            steps:
            - task: ServiceNow-DevOps-Agent-Job-Notification@1
              inputs:
                connectedServiceName: 'amarchange'
                upstream: 'j4'
                Phase: 'STARTED'
              continueOnError: true
            - task: ServiceNow-DevOps-Agent-Job-Notification@1
              inputs:
                connectedServiceName: 'amarchange'
                upstream: 'j4'
                Phase: 'COMPLETED'
              continueOnError: true